# image: https://hub.docker.com/r/bitnami/suitecrm
# docs: https://github.com/bitnami/bitnami-docker-suitecrm


version: '3.8'

services:
  suitecrm:
    image: ossrs/srs:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - '${APP_HTTP_PORT}:8080'
    environment:
      - SUITECRM_DATABASE_HOST=mysql
      - SUITECRM_DATABASE_PORT_NUMBER=${DB_MYSQL_PORT}
    volumes:
      - 'suitecrm:/bitnami/suitecrm'

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  mysql:
  suitecrm:
