# image: https://hub.docker.com/r/bitnami/suitecrm
# docs: https://github.com/bitnami/bitnami-docker-suitecrm


version: '3.8'

services:
  srs:
    image: ossrs/srs:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: always
    ports:
      - '${APP_HTTP_PORT}:8080'
      - '1935:1935'
      - '1985:1985'
      - '8000:8000'
    environment:
      - CANDIDATE=${APP_URL}

  ffmpeg:
    image: ossrs/srs:encoder
    container_name: ${APP_NAME}-ffmpeg
    restart: always
    environment:
      - SOURCE=./src/flv/source.flv
      - URL=rtmp://${APP_URL}/live/livestream
      
networks:
  default:
    name: ${APP_NETWORK}
    external: true
